name: Oracle GraalVM Early Access build
on: [push, pull_request]
jobs:
  build:
    strategy:
       matrix:
         arch: [ ubuntu-24.04, kylin-arm ]
         build-type: [ libc, musl ]
         include:
           - build-type: musl
             build-args: '-P musl'
           - build-type: libc
             build-args: ''
         exclude:
           - arch: ubuntu-24.04
             build-type: libc
           - arch: kylin-arm
             build-type: musl
    runs-on: ${{ matrix.arch }}
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17'
          distribution: 'graalvm-community'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-musl: ${{ matrix.build-type == 'musl' }}
      - name: Build Native
        run: |
          java --version
          native-image --version
          mvn clean native:compile -P native ${{ matrix.build-args }} -DskipTests
          cd target
          mv ktna-nav-project ktna-nav
          tar -czvf ktna-nav-${{ matrix.arch }}.tar ktna-nav
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: ktna-nav-${{ matrix.arch }}.tar
          path: target/ktna-nav-${{ matrix.arch }}.tar
